[versions]
androidGradlePlugin = "8.13.0"
kotlin = "2.2.10"
androidxCore = "1.17.0"
androidxLifecycle = "2.9.4"
androidxActivity = "1.11.0"
compose = "1.9.4"
material3 = "1.5.0-alpha08"
androidMaterial = "1.13.0"
materialKolor = "4.0.4"
androidxTest = "1.7.0"
junit = "4.13.2"
androidxTestExt = "1.3.0"
androidxTestEspresso = "3.7.0"
lazyColumnScrollbar = "1.7.2"
decomposite = "0.2.1.0-p0"
realm = "3.2.9"
androidx-splashscreen = "1.2.0"
evolpagink = "0.5.0"
localina = "1.0.0-alpha3"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
google-android-material = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
materialkolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidxTest" }
androidx-compose-animation-tooling-internal = { module = "androidx.compose.animation:animation-tooling-internal", version.ref = "compose" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version = "1.7.0-alpha06" }
lazycolumnscrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazyColumnScrollbar" }
decomposite = { module = "com.nxoim:decomposite", version.ref = "decomposite" }
realm-library-base = { module = "com.infomaniak.realm.kotlin:library-base", version.ref = "realm"}
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
evolpagink = { module = "com.nxoim.evolpagink:compose", version.ref = "evolpagink"}
localina = { module = "io.github.sudarshanmhasrup.localina:localina", version.ref = "localina"}


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
realm = { id = "com.infomaniak.realm.kotlin", version.ref = "realm" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }